const graph = require('graph-data-structure')
const busStops = graph()
busStops.addNode('Red Oak Lane')
busStops.addNode('Lipman Hall')
busStops.addNode('College Hall')
busStops.addNode('Socam')
busStops.addNode('Biel Road')
busStops.addNode('Henderson')
busStops.addNode('Gibbons')
busStops.addNode('The Yard')
busStops.addNode('College Ave Student Center')
busStops.addNode('Student Activities Center')
busStops.addNode('Hill Center')
busStops.addNode('Allison Road Classrooms/Science Buildings')
busStops.addNode('Busch Student Center')
busStops.addNode('Livingston Plaza')
busStops.addNode('Livingston Student Center')